<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
	<!--<TargetFramework>net8.0-windows</TargetFramework>-->
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
	<LangVersion>10</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ImageData\WorldObjects\Animal_SpaceDragon.png" />
    <None Remove="ImageData\WorldObjects\Animal_SpaceMantaray.png" />
    <None Remove="ImageData\WorldObjects\Animal_SpaceWhale.png" />
    <None Remove="ImageData\WorldObjects\Base_MerchantVille.png" />
    <None Remove="ImageData\WorldObjects\Bullet_StarMine_Med.png" />
    <None Remove="ImageData\WorldObjects\Ship_Navy_Tender_Wrecked.png" />
    <None Remove="ImageData\WorldObjects\Ship_Pirate_Carrack_Wrecked.png" />
    <None Remove="ImageData\WorldObjects\Ship_Pirate_FastFrigate_Wrecked.png" />
    <None Remove="ImageData\WorldObjects\Ship_Pirate_JollyRoger_Wrecked.png" />
    <None Remove="ImageData\WorldObjects\Terrain_Cresentia_Distant.png" />
    <None Remove="ImageData\WorldObjects\Terrain_Moon_Parliament.png" />
    <None Remove="ImageData\WorldObjects\Terrain_Moon_Pirate.png" />
    <None Remove="ImageData\WorldObjects\Terrain_Moon_Rocky.png" />
    <None Remove="ImageData\WorldObjects\Terrain_Planet_Jupitron.png" />
    <None Remove="ImageData\WorldObjects\Terrain_Planet_Osmosis.png" />
    <None Remove="ImageData\WorldObjects\Terrain_Planet_Parliament.png" />
    <None Remove="ImageData\WorldObjects\Terrain_Planet_Ringo.png" />
    <None Remove="ImageData\WorldObjects\Terrain_Planet_Shattered.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ImageData\WorldObjects.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Animal_SpaceDragon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Animal_SpaceMantaray.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Animal_SpaceWhale.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Asteroid_Darkmatter1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Asteroid_Darkmatter2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Asteroid_Darkmatter3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Asteroid_Darkmatter4.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Asteroid_Huge.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Asteroid_Large.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Asteroid_Large_Armed.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Asteroid_Med.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Asteroid_Med_Armed1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Asteroid_Med_Armed2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Asteroid_Small.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Asteroid_Small_Armed.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Base_AbandonedCamp.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Base_Alamein.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Base_Artem.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Base_Cresentia.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Base_Depot.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Base_Dolinor.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Base_Dolinor_Mission8.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Base_Grant.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Base_IroncladMines.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Base_MerchantVille.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Base_MiningCamp.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Base_Montgomery.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Base_Pirate.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Base_PirateMP.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Base_PirateMP_3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Base_PirateStockade.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Base_PortIvy.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Base_Procyon1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Base_Procyon2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Base_QueensPalace.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Base_Regina.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Base_Safetytown.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Base_ShipyardFreemason.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Base_Sloggoville.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Base_SmugglersCamp.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Base_Whocaresville.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Bullet_StarMine_Med.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island01.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island02.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island03.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island04.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island05.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island06.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island07.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island08.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island09.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island10.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island11.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island12.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island13.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island14.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_DockBouy.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Dragon_01.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Dragon_02.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Dragon_03.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Dragon_04.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Dragon_05.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Dragon_06.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Dragon_07.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Dragon_08.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Icy_01.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Icy_02.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Icy_03.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Icy_04.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Icy_05.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Icy_06.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Large01.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Lighthouse.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Med01.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Med02.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Med03.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Med04.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Med05.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Med06.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Med07.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Med08.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Med09.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Mega_01.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Mega_02.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Mega_03.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Mega_03_tutorial.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Mega_04.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Mega_05.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Mega_06.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Rocky_01.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Rocky_02.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Rocky_03.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Rocky_04.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Rocky_05.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Rocky_06.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Rocky_07.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Rocky_08.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Small01.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Volcano_01.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Volcano_02.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Volcano_03.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Volcano_04.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Volcano_05.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Volcano_06.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Island_Volcano_07.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_CivilianFishingBoat01.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_CivilianFishingBoat02.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Civilian_Barque.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Civilian_Barque_Wrecked.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Civilian_Galleon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Civilian_Galleon_Feather.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Civilian_Galleon_Wrecked.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Civilian_Lifeboat.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Civilian_Merchant.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Civilian_Packet.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Civilian_Schooner.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Civilian_Schooner_Feather.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Civilian_Sloop.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_Assault_Cutter.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_Cutter.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_CutterNIS.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_Cutter_Tutorial.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_FastFrigate.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_Frigate.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_Frigate_Feather.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_Frigate_NIS.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_Heavy_Escort.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_Heavy_Escort_Amelia.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_Legacy.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_Lifeboat.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_Lifeboat_Mission9.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_ManOWar.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_ManOWar_Feather.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_Minelayer.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_Sloop.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_StarHammer.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_StarHammer_Wrecked.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_Tender.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_Tender_Feather.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_Tender_Wrecked.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_Torpedo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_Torpedo_Jim.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_Torpedo_Tutorial.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_Tug.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Navy_Weapon_Barge.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Pirate_Assault_Cutter.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Pirate_Barque.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Pirate_Carrack.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Pirate_Carrack_Wrecked.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Pirate_FastAttack.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Pirate_FastFrigate_Wrecked.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Pirate_Galleon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Pirate_Gunboat.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Pirate_JollyRoger_Wrecked.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Pirate_Lifeboat.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Pirate_Schooner.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Pirate_Silver.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Pirate_Sloop.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Pirate_Tender.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Pirate_Weapon_Barge.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Procyon_Barge.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Procyon_Cruiser.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Procyon_Cutter.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Procyon_Destroyer.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Procyon_Destroyer_FastTurn.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Procyon_Dreadnought.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Procyon_Dreadnought_Feather.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Procyon_Frigate.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Procyon_Gunboat.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Procyon_IceFist.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Procyon_Lifeboat.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Procyon_ManOWar.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Procyon_Minelayer.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Procyon_RefuelingStation.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Procyon_Sloop.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Procyon_Submersible.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Procyon_Tender.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_Target.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Ship_WeaponBarge.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Terrain_Cresentia_Distant.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Terrain_Moon_Parliament.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Terrain_Moon_Pirate.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Terrain_Moon_Rocky.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Terrain_Planet_Jupitron.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Terrain_Planet_Osmosis.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Terrain_Planet_Parliament.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Terrain_Planet_Ringo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ImageData\WorldObjects\Terrain_Planet_Shattered.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CalcBinding" Version="2.5.2" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="LibZ.Tool" Version="1.2.0" />
  </ItemGroup>

  <Target Name="Libz" AfterTargets="AfterBuild" Condition="$(Configuration) == Release">
    <Exec Command="$(PkgLibz_Tool)\Tools\libz.exe inject-dll --assembly $(ProjectDir)bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).exe --include $(ProjectDir)bin\$(Configuration)\$(TargetFramework)\*.dll --move" />
  </Target>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\AlphaBg.png" />
    <Resource Include="Images\Arrow.png" />
    <Resource Include="Images\bg.png" />
    <Resource Include="Images\Default.png" />
    <Resource Include="Images\Move.png" />
    <Resource Include="Images\ObjectivePoint.png" />
    <Resource Include="Images\Player.png" />
    <Resource Include="Images\WotPlaceholder.png" />
  </ItemGroup>

</Project>
